name: Credential Management
description: Request for getting access to 1Password or having a new vault created
title: Credential Management Request - [YOUR NAME AND PROJECT]
labels: ['operations']
assignees:
  - jmertic
body:
  - type: markdown
    attributes:
      value: |
        Please provide your name and project in the title in place of `[YOUR NAME AND PROJECT]`, and then detail the request below.
  - type: textarea
    id: details
    attributes:
      label: Request details
