name: New Mailing List
description: Requesting a new mailing list at https://lists.openmainframeproject.org
title: New Mailing List - [PROJECT]
labels: ['infrastructure request']
assignees: 
  - jmertic
  - Yarille
body:
  - type: markdown
    attributes:
      value: |
        Please put the name of your project in the title above in place of PROJECT, and then complete all the sections below to request a new mailing list. Requests can take a day or two, so please be patient :-).
  - type: checkboxes
    id: list-preference
    attributes:
      label: Would you like a combined -user and -dev list, or seperate
      description: You may select more than one.
      options:
        - label: Combined -user and -dev list
        - label: Seperate -user and -dev list
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Moderators for the mailing list
      description: Please list names and email addresses
    validations:
      required: true
