name: New guest blog post
description: Submit a new guest blog post for consideration for Open Mainframe Project blog
title: New blog - [POST NAME]
labels: ['blog']
assignees: 
  - Maemalynn
body:
  - type: markdown
    attributes:
      value: |
        Please add the name of your blog post in the title in place of `[POST NAME]`, and then complete the below form to submit a blog post for consideration for Open Mainframe Project blog. All blog posts are will be reviewed by the LF staff to ensure it meets the [branding guidelines](https://github.com/openmainframeproject/foundation/blob/master/BRANDING_GUIDELINES.md) and potentially reviewed by an SME to ensure accuracy ( both of whom will work with you to make any changes needed )
  - type: textarea
    id: blog
    attributes:
      label: Blog content ( or provide link to blog content
    validations:
      required: true
  - type: input
    id: target-audience
    attributes:
      label: Target audience
    validations:
      required: true
  - type: input
    id: target-date
    attributes:
      label: Target date to post
      description: Please allow 1 week for reviews and coordination
    validations:
      required: true
