name: New Slack channel
description: Requesting a new Slack channel in the OMP Slack organization
title: New Slack Channel - [CHANNEL]
labels: infrastructure request
assignees: 
  - jmertic
  - Yarille
body:
  - type: markdown
    attributes:
      value: |
        Please put the name of the channel in the title above in place of `[CHANNEL]`, and then complete all the sections below to request a new channel. Channel requests can take a day or two, so please be patient :-).
  - type: textarea
    id: purpose
    attributes:
      label: Channel purpose
    validations:
      required: true
  - type: textarea
    id: moderators
    attributes:
      label: Moderators for the channel
    validations:
      required: true
  - type: textarea
    id: lifespan
    attributes:
      label: Does this channel have a lifespan?
      description: If the channel does have a lifespan, please let us know when that is so we can archive it or mark it inactive
    validations:
      required: true
