name: Webinar proposal
description: Submit your title and abstract for an Open Mainframe Project webinar
title: Webinar - [TITLE]
labels: webinar
assignees: 
  - Maemalynn
body:
  - type: markdown
    attributes:
      value: |
        Please provide the proposed title of your presentation in the title in place of `[TITLE]`, and then complete the form below. Please refer to the webinar guidelines at https://github.com/openmainframeproject/foundation/blob/master/WEBINAR-GUIDELINES.md before submitting.
  - type: textarea
    id: abstract
    attributes:
      label: Abstract
    validations:
      required: true
  - type: textarea
    id: target-audience
    attributes:
      label: Speaker(s) Information
      description: |
        For each speaker provide:
          - Headshot ( drag and drop to attach )
          - Title
          - Company
          - Bio
          - Email addresses for all speakers/panelists    
  - type: input
    id: target-date
    attributes:
      label: Desired Webinar Date
      description: Please allow 1 week for reviews and coordination
